### PR TITLE
Fixed Imgui Mouse Position issue 

### LINKED ISSUE #13: Imgui mouse position not matching input
**Describe the bug**
When moving imgui windows in the program, the position failed to match up with the mouse. 

**To Reproduce**
1. Launch the launcher.
2. Attempt to move the imgui window.

**Expected behavior**
The mouse movements should align with the window movements.

**Additional context**

### PR DESCRIPTION
**Pull request by Ninetime**
Fixes #13 .

### CODE REVIEW

File: src/sidecar/sidecar.cxx [hunk 1]
```diff
@@ -32,12 +33,14 @@ static bool(__cdecl* RealSteamAPI_Init)();
...
 
 static ImGuiIO g_io;
+//static MemoryEditor mem_edit_1;
 
 DWORD FakeInitializeLibraries() {
 	g_hwnd = *(HWND*)(g_lpPEHeaderRoot + (0xeb6554 - 0x9b0000));
 
 	IMGUI_CHECKVERSION();
 	ImGui::CreateContext();
+	ImGui::GetIO().MouseDrawCursor = true;
```
Comment (adanducci) [inline src/sidecar/sidecar.cxx]: You can just set this on the `g_io` object we retrieve on the line below.
